name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: ./tools/flatc --kotlin --gen-all -o kotlin definitions/ethersCommand/main.fbs
      - run: ./tools/flatc --swift --gen-all -o swift definitions/ethersCommand/main.fbs
      - run: cp -r web kotlin/
      - run: cp -r web swift/
      - run: zip -r kotlin.zip kotlin
      - run: zip -r swift.zip swift
      - run: unzip -l kotlin.zip
      - run: unzip -l swift.zip
      - run: echo $GITHUB_ENV
      - run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\""